### ISSUE TITLE
CN-W0D5 Statistics Tutorial 2 Video 5: Statistics

### ISSUE THREAD

**Issue by ogulyurdakul** [NeuromatchAcademy/precourse#114]
On the video at this link (https://youtu.be/1Q3VqcpfvBk?t=35) the Bayes' rule is stated incorrectly, as a division by the joint density/probability as opposed to the marginal. Here's the screenshot:
![image](https://github.com/NeuromatchAcademy/course-content/assets/42587007/c2358f05-9107-457c-807a-75d99a7e6eb2)

**Comment by spirosChv** [comment]
@ogulyurdakul thank you for reporting this. I have added a comment below the video to clarify this. https://github.com/NeuromatchAcademy/precourse/pull/117 resolves this issue.

**Comment by ogulyurdakul** [comment]
I don't think I see it yet, is it on the notebooks, video comments or the video captions?

**Comment by spirosChv** [comment]
@ogulyurdakul have you cecked the code and the PR?

**Comment by ogulyurdakul** [comment]
I hadn't, I checked the published notebooks directly from the website those on Colab. I guess the changes are not published yet, then?

**Comment by spirosChv** [comment]
You have checked the jupyterbook, not the published notebooks. To check the notebook you need to open it clicking the badge. Anyways, the issue has been fixed.
