### ISSUE TITLE
tutorials/W0D1_PythonWorkshop1/solutions/W0D1_Tutorial1_Solution_4441778c.py

### ISSUE THREAD

**Issue by Devadeut** [NeuromatchAcademy/precourse#115]
small approvement in 
 1.# Plot mean + standard deviation with alpha=0.8 and argument 'C7'
as # Plot mean + standard deviation with alpha=0.8 and argument 'C7.'

 2.# Plot mean - standard deviation with alpha=0.8 and argument 'C7'
as # Plot mean - standard deviation with alpha=0.8 and argument 'C7.'

**Comment by spirosChv** [comment]
@Devadeut Good catch, thank you. https://github.com/NeuromatchAcademy/precourse/pull/117 resolves this.
