### ISSUE TITLE
Update year in enrollmentforms/funding_template.md 

### ISSUE THREAD

**Issue by likeajumprope** [NeuromatchAcademy/precourse#39]
Figured while enrolling thatr enrollmentforms/funding_template.md still says 2021 instead of 2022.
Created PR #38 to fix issue.

**Comment by spirosChv** [comment]
Thank you for reporting this. However, our contributor policy can be found [here](https://github.com/NeuromatchAcademy/precourse/blob/main/.github/contributing.md).
