### ISSUE TITLE
Variance vs standard deviation mixup in W0D5 coding exercise 2.2

### ISSUE THREAD

**Issue by boydmeredith** [NeuromatchAcademy/precourse#57]
The exercise asks us to write a function `negLogLike` to fit the mean and variance of a gaussian, but the code that uses this function and the solution treat the scale variable as a standard deviation. This doesn't matter much in the exercise because the generative value is 1, but will break if we try to recover other values.

**Comment by spirosChv** [comment]
Good catch! Indeed in `scipy.stats.norm` argument called `scale` represents the standard deviation.

"The location (loc) keyword specifies the mean. The scale (scale) keyword specifies the standard deviation." taken from: [scipy.stats.norm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html) documentation. Thank you for reporting it.
